/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as PrsRouteImport } from './routes/prs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrsIndexRouteImport } from './routes/prs.index'
import { Route as BugsIndexRouteImport } from './routes/bugs.index'
import { Route as PrsPrIdRouteImport } from './routes/prs.$prId'
import { Route as BugsBugIdRouteImport } from './routes/bugs.$bugId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsRoute = PrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsIndexRoute = PrsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrsRoute,
} as any)
const BugsIndexRoute = BugsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BugsRoute,
} as any)
const PrsPrIdRoute = PrsPrIdRouteImport.update({
  id: '/$prId',
  path: '/$prId',
  getParentRoute: () => PrsRoute,
} as any)
const BugsBugIdRoute = BugsBugIdRouteImport.update({
  id: '/$bugId',
  path: '/$bugId',
  getParentRoute: () => BugsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/bugs': typeof BugsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/prs': typeof PrsRouteWithChildren
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/prs/$prId': typeof PrsPrIdRoute
  '/bugs/': typeof BugsIndexRoute
  '/prs/': typeof PrsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/prs/$prId': typeof PrsPrIdRoute
  '/bugs': typeof BugsIndexRoute
  '/prs': typeof PrsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/bugs': typeof BugsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/prs': typeof PrsRouteWithChildren
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/prs/$prId': typeof PrsPrIdRoute
  '/bugs/': typeof BugsIndexRoute
  '/prs/': typeof PrsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branches'
    | '/bugs'
    | '/components'
    | '/dashboard'
    | '/prs'
    | '/repos'
    | '/settings'
    | '/users'
    | '/bugs/$bugId'
    | '/prs/$prId'
    | '/bugs/'
    | '/prs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/branches'
    | '/components'
    | '/dashboard'
    | '/repos'
    | '/settings'
    | '/users'
    | '/bugs/$bugId'
    | '/prs/$prId'
    | '/bugs'
    | '/prs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branches'
    | '/bugs'
    | '/components'
    | '/dashboard'
    | '/prs'
    | '/repos'
    | '/settings'
    | '/users'
    | '/bugs/$bugId'
    | '/prs/$prId'
    | '/bugs/'
    | '/prs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRoute
  BugsRoute: typeof BugsRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  DashboardRoute: typeof DashboardRoute
  PrsRoute: typeof PrsRouteWithChildren
  ReposRoute: typeof ReposRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs': {
      id: '/prs'
      path: '/prs'
      fullPath: '/prs'
      preLoaderRoute: typeof PrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs/': {
      id: '/prs/'
      path: '/'
      fullPath: '/prs/'
      preLoaderRoute: typeof PrsIndexRouteImport
      parentRoute: typeof PrsRoute
    }
    '/bugs/': {
      id: '/bugs/'
      path: '/'
      fullPath: '/bugs/'
      preLoaderRoute: typeof BugsIndexRouteImport
      parentRoute: typeof BugsRoute
    }
    '/prs/$prId': {
      id: '/prs/$prId'
      path: '/$prId'
      fullPath: '/prs/$prId'
      preLoaderRoute: typeof PrsPrIdRouteImport
      parentRoute: typeof PrsRoute
    }
    '/bugs/$bugId': {
      id: '/bugs/$bugId'
      path: '/$bugId'
      fullPath: '/bugs/$bugId'
      preLoaderRoute: typeof BugsBugIdRouteImport
      parentRoute: typeof BugsRoute
    }
  }
}

interface BugsRouteChildren {
  BugsBugIdRoute: typeof BugsBugIdRoute
  BugsIndexRoute: typeof BugsIndexRoute
}

const BugsRouteChildren: BugsRouteChildren = {
  BugsBugIdRoute: BugsBugIdRoute,
  BugsIndexRoute: BugsIndexRoute,
}

const BugsRouteWithChildren = BugsRoute._addFileChildren(BugsRouteChildren)

interface PrsRouteChildren {
  PrsPrIdRoute: typeof PrsPrIdRoute
  PrsIndexRoute: typeof PrsIndexRoute
}

const PrsRouteChildren: PrsRouteChildren = {
  PrsPrIdRoute: PrsPrIdRoute,
  PrsIndexRoute: PrsIndexRoute,
}

const PrsRouteWithChildren = PrsRoute._addFileChildren(PrsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BranchesRoute: BranchesRoute,
  BugsRoute: BugsRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  DashboardRoute: DashboardRoute,
  PrsRoute: PrsRouteWithChildren,
  ReposRoute: ReposRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
