/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as PrsRouteImport } from './routes/prs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrsIndexRouteImport } from './routes/prs.index'
import { Route as PrsPrIdRouteImport } from './routes/prs.$prId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsRoute = PrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsIndexRoute = PrsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrsRoute,
} as any)
const PrsPrIdRoute = PrsPrIdRouteImport.update({
  id: '/$prId',
  path: '/$prId',
  getParentRoute: () => PrsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/prs': typeof PrsRouteWithChildren
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/prs/$prId': typeof PrsPrIdRoute
  '/prs/': typeof PrsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/prs/$prId': typeof PrsPrIdRoute
  '/prs': typeof PrsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/prs': typeof PrsRouteWithChildren
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/prs/$prId': typeof PrsPrIdRoute
  '/prs/': typeof PrsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/prs'
    | '/repos'
    | '/settings'
    | '/users'
    | '/prs/$prId'
    | '/prs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/repos'
    | '/settings'
    | '/users'
    | '/prs/$prId'
    | '/prs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/prs'
    | '/repos'
    | '/settings'
    | '/users'
    | '/prs/$prId'
    | '/prs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  PrsRoute: typeof PrsRouteWithChildren
  ReposRoute: typeof ReposRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs': {
      id: '/prs'
      path: '/prs'
      fullPath: '/prs'
      preLoaderRoute: typeof PrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs/': {
      id: '/prs/'
      path: '/'
      fullPath: '/prs/'
      preLoaderRoute: typeof PrsIndexRouteImport
      parentRoute: typeof PrsRoute
    }
    '/prs/$prId': {
      id: '/prs/$prId'
      path: '/$prId'
      fullPath: '/prs/$prId'
      preLoaderRoute: typeof PrsPrIdRouteImport
      parentRoute: typeof PrsRoute
    }
  }
}

interface PrsRouteChildren {
  PrsPrIdRoute: typeof PrsPrIdRoute
  PrsIndexRoute: typeof PrsIndexRoute
}

const PrsRouteChildren: PrsRouteChildren = {
  PrsPrIdRoute: PrsPrIdRoute,
  PrsIndexRoute: PrsIndexRoute,
}

const PrsRouteWithChildren = PrsRoute._addFileChildren(PrsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  PrsRoute: PrsRouteWithChildren,
  ReposRoute: ReposRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
